name: CI

on: repository_dispatch
  
jobs:
  one:
    runs-on:
      pool: default
    services:
      nginx:
        image: nginx
        ports:
        - 127.0.0.1:8080:80/tcp
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$JOB_CONTEXT"
      - name: Check service endpoint
        run: |
          curl 0.0.0.0:${{ job.services.nginx.ports['80'] }} || exit 1
          echo "----------------------------------------"
          curl localhost:${{ job.services.nginx.ports['80'] }} || exit 1
  two:
    needs: one
    runs-on:
      pool: default
    services:
      nginx: nginx
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$JOB_CONTEXT"
